Traceback (most recent call last):
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mmann1123/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(dpi=200)
with gw.open([l8_224078_20200518_B2, l8_224078_20200518_B3, l8_224078_20200518_B4],
              stack_dim='band') as src:
    src.where(src != 0).sel(band=[3, 2, 1]).gw.imshow(robust=True, ax=ax)
plt.tight_layout(pad=1)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mInvalidIndexError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-5-5eb672b54e84>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m with gw.open([l8_224078_20200518_B2, l8_224078_20200518_B3, l8_224078_20200518_B4],
[1;32m      3[0m               stack_dim='band') as src:
[0;32m----> 4[0;31m     [0msrc[0m[0;34m.[0m[0mwhere[0m[0;34m([0m[0msrc[0m [0;34m!=[0m [0;36m0[0m[0;34m)[0m[0;34m.[0m[0msel[0m[0;34m([0m[0mband[0m[0;34m=[0m[0;34m[[0m[0;36m3[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mgw[0m[0;34m.[0m[0mimshow[0m[0;34m([0m[0mrobust[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0max[0m[0;34m=[0m[0max[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mtight_layout[0m[0;34m([0m[0mpad[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/xarray/core/dataarray.py[0m in [0;36msel[0;34m(self, indexers, method, tolerance, drop, **indexers_kwargs)[0m
[1;32m   1257[0m             [0mmethod[0m[0;34m=[0m[0mmethod[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1258[0m             [0mtolerance[0m[0;34m=[0m[0mtolerance[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1259[0;31m             [0;34m**[0m[0mindexers_kwargs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1260[0m         )
[1;32m   1261[0m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_from_temp_dataset[0m[0;34m([0m[0mds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/xarray/core/dataset.py[0m in [0;36msel[0;34m(self, indexers, method, tolerance, drop, **indexers_kwargs)[0m
[1;32m   2229[0m         [0mindexers[0m [0;34m=[0m [0meither_dict_or_kwargs[0m[0;34m([0m[0mindexers[0m[0;34m,[0m [0mindexers_kwargs[0m[0;34m,[0m [0;34m"sel"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2230[0m         pos_indexers, new_indexes = remap_label_indexers(
[0;32m-> 2231[0;31m             [0mself[0m[0;34m,[0m [0mindexers[0m[0;34m=[0m[0mindexers[0m[0;34m,[0m [0mmethod[0m[0;34m=[0m[0mmethod[0m[0;34m,[0m [0mtolerance[0m[0;34m=[0m[0mtolerance[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2232[0m         )
[1;32m   2233[0m         [0mresult[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0misel[0m[0;34m([0m[0mindexers[0m[0;34m=[0m[0mpos_indexers[0m[0;34m,[0m [0mdrop[0m[0;34m=[0m[0mdrop[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/xarray/core/coordinates.py[0m in [0;36mremap_label_indexers[0;34m(obj, indexers, method, tolerance, **indexers_kwargs)[0m
[1;32m    415[0m [0;34m[0m[0m
[1;32m    416[0m     pos_indexers, new_indexes = indexing.remap_label_indexers(
[0;32m--> 417[0;31m         [0mobj[0m[0;34m,[0m [0mv_indexers[0m[0;34m,[0m [0mmethod[0m[0;34m=[0m[0mmethod[0m[0;34m,[0m [0mtolerance[0m[0;34m=[0m[0mtolerance[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    418[0m     )
[1;32m    419[0m     [0;31m# attach indexer's coordinate to pos_indexers[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/xarray/core/indexing.py[0m in [0;36mremap_label_indexers[0;34m(data_obj, indexers, method, tolerance)[0m
[1;32m    268[0m             [0mcoords_dtype[0m [0;34m=[0m [0mdata_obj[0m[0;34m.[0m[0mcoords[0m[0;34m[[0m[0mdim[0m[0;34m][0m[0;34m.[0m[0mdtype[0m[0;34m[0m[0;34m[0m[0m
[1;32m    269[0m             [0mlabel[0m [0;34m=[0m [0mmaybe_cast_to_coords_dtype[0m[0;34m([0m[0mlabel[0m[0;34m,[0m [0mcoords_dtype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 270[0;31m             [0midxr[0m[0;34m,[0m [0mnew_idx[0m [0;34m=[0m [0mconvert_label_indexer[0m[0;34m([0m[0mindex[0m[0;34m,[0m [0mlabel[0m[0;34m,[0m [0mdim[0m[0;34m,[0m [0mmethod[0m[0;34m,[0m [0mtolerance[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    271[0m             [0mpos_indexers[0m[0;34m[[0m[0mdim[0m[0;34m][0m [0;34m=[0m [0midxr[0m[0;34m[0m[0;34m[0m[0m
[1;32m    272[0m             [0;32mif[0m [0mnew_idx[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/xarray/core/indexing.py[0m in [0;36mconvert_label_indexer[0;34m(index, label, index_name, method, tolerance)[0m
[1;32m    198[0m                     [0;34m"MultiIndex variable: "[0m [0;34m+[0m [0mindex_name[0m[0;34m[0m[0;34m[0m[0m
[1;32m    199[0m                 )
[0;32m--> 200[0;31m             [0mindexer[0m [0;34m=[0m [0mget_indexer_nd[0m[0;34m([0m[0mindex[0m[0;34m,[0m [0mlabel[0m[0;34m,[0m [0mmethod[0m[0;34m,[0m [0mtolerance[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    201[0m             [0;32mif[0m [0mnp[0m[0;34m.[0m[0many[0m[0;34m([0m[0mindexer[0m [0;34m<[0m [0;36m0[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    202[0m                 [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0;34mf"not all values found in index {index_name!r}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/xarray/core/indexing.py[0m in [0;36mget_indexer_nd[0;34m(index, labels, method, tolerance)[0m
[1;32m    101[0m     """
[1;32m    102[0m     [0mflat_labels[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mravel[0m[0;34m([0m[0mlabels[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 103[0;31m     [0mflat_indexer[0m [0;34m=[0m [0mindex[0m[0;34m.[0m[0mget_indexer[0m[0;34m([0m[0mflat_labels[0m[0;34m,[0m [0mmethod[0m[0;34m=[0m[0mmethod[0m[0;34m,[0m [0mtolerance[0m[0;34m=[0m[0mtolerance[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    104[0m     [0mindexer[0m [0;34m=[0m [0mflat_indexer[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0mlabels[0m[0;34m.[0m[0mshape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    105[0m     [0;32mreturn[0m [0mindexer[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pygisbookgw/lib/python3.7/site-packages/pandas/core/indexes/base.py[0m in [0;36mget_indexer[0;34m(self, target, method, limit, tolerance)[0m
[1;32m   3170[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0mis_unique[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3171[0m             raise InvalidIndexError(
[0;32m-> 3172[0;31m                 [0;34m"Reindexing only valid with uniquely valued Index objects"[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3173[0m             )
[1;32m   3174[0m [0;34m[0m[0m

[0;31mInvalidIndexError[0m: Reindexing only valid with uniquely valued Index objects
InvalidIndexError: Reindexing only valid with uniquely valued Index objects

